name: Build
on: [push]
env:
  project: ics2csv4all
jobs:
  build:
    name: build ics2csv4all for ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: [x86_64-pc-windows-gnu, x86_64-unknown-linux-musl]
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: Compile and release
        id: compile
        uses: rust-build/rust-build.action@v1.4.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          RUSTTARGET: ${{ matrix.target }}
          EXTRA_FILES: "README.md LICENSE"
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.project }}-${{ matrix.target }}
          path: |
            ${{ steps.compile.outputs.BUILT_ARCHIVE }}
            ${{ steps.compile.outputs.BUILT_CHECKSUM }}
  release:
    if: github.ref_type == 'tag'
    name: release ics2csv4all
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false 
    steps:   
    - name: Create release
      id: create_release
      uses: actions/create-release@v1.1.4
      with:
        draft: false
        prerelease: false
        release_name: ics2csv4all ${{ github.ref }}
        tag_name: ${{ github.ref }}
        body_path: CHANGELOG.md
      env:
        GITHUB_TOKEN: ${{ github.token }}
    - name: Upload windows artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}                     
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path:  /home/runner/work/ics2csv4all/ics2csv4all/output/ics2csv4all-x86_64-pc-windows-gnu.zip
        asset_name: ics2csv4all-x86_64-pc-windows-gnu.zip
        asset_content_type: application/zip
    - name: Upload linux artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}                     
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path:  /home/runner/work/ics2csv4all/ics2csv4all/output/ics2csv4all-x86_64-unknown-linux-musl.zip
        asset_name: ics2csv4all-x86_64-unknown-linux-musl.zip
        asset_content_type: application/zip        